### ISSUE TITLE
DNMModel.framework: No such file or directory

### ISSUE THREAD

**Issue by AlesTsurko** [jsbean/DNMKit#76]
Hi James. I've read about dnem on your site and it looks very interesting!

I'm trying to build DNM Text Editor.app target, but get the linking issue. I've tried to build DNMModel.framework separately, but nothing changes in products - it looks like I'm not get DNMModel.framewrok for OSX. But, DNMModel.framework for iOS (from DNMModel project) builds fine. And also I get two products when I build DNMModel.framework for iOS. As if there was no difference between OS X and iOS targets or the iOS would build both.

Then, when I get those two frameworks through building DNMModel_iOS (DNMModel project), XCode allows me to embed DNMModel.framework (for OSX!) in DNM Text Editor Target. I embed, build and Xcode give me this:

```
CodeSign /Users/alestsurko/Library/Developer/Xcode/DerivedData/DNM-amlmxiyaszdnuabzsvdrtagyoajx/Build/Products/Debug/DNM\ Text\ Editor.app/Contents/Frameworks/DNMModel.framework/Versions/A
    cd "/Users/alestsurko/Downloads/DNMKit-master/DNM Text Editor"
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "Mac Developer: ales.tsurko@gmail.com (MWN42JG99S)"

    /usr/bin/codesign --force --sign 9A458A5F3C5E513B3D2DAF15DCD24FC12DBC47FF --preserve-metadata=identifier,entitlements --timestamp=none /Users/alestsurko/Library/Developer/Xcode/DerivedData/DNM-amlmxiyaszdnuabzsvdrtagyoajx/Build/Products/Debug/DNM\ Text\ Editor.app/Contents/Frameworks/DNMModel.framework/Versions/A

/Users/alestsurko/Library/Developer/Xcode/DerivedData/DNM-amlmxiyaszdnuabzsvdrtagyoajx/Build/Products/Debug/DNM Text Editor.app/Contents/Frameworks/DNMModel.framework/Versions/A: No such file or directory
Command /usr/bin/codesign failed with exit code 1
```

I've tried to change the workspace's build location to relative to derived data, adding the framework building to the DNM Text Editor scheme, but nothing helps...

**Comment by AlesTsurko** [comment]
Found it! I just changed Code Signing Identity to Don't Code Sign and now it works.

**Comment by jsbean** [comment]
@AlesTsurko,

Thanks so much for all this work! I merged these updates with #77.

Apologies if this is a bit mangled on the inside. I've got some cleaning to do. Working on it.

One question: now, after this update, I have to remove the frameworks from each app target (DNM_iOS and DNM Text Editor) and re-add them to the "Embedded Binaries", as they seem to be tagged with an absolute path to your machine (as it was with mine).

Is there a way to set the paths to a relative path, or must each user re-plug the frameworks in, to reset the path. I assume there must be a way.

Many thanks, again!

James

**Comment by jsbean** [comment]
As far as I can tell, this is fixed with d71f071992b610410c1fc39372885ed94ef7b9fb.

Thanks, @AlesTsurko!

**Comment by AlesTsurko** [comment]
Not completely... I just updated my local repository and found absolute path in iOS app. It was because of merge issues. I'll send a pull request.

**Comment by jsbean** [comment]
Oh whoops!

**Comment by jsbean** [comment]
Things are working on my end. I'll make a commit to make sure I'm not screwing up anything with this.

**Comment by jsbean** [comment]
Let me know if you are finding any other issues with that. I shall close this once again.
